# In order not to overlap with other applications.
server.port=9090

dou.training.set.csv.file.path=
dou.regression.model.directory.path=models/dou-regression
dou.clustering.model.directory.path=models/dou-clustering

product.training.set.csv.file.path=
product.test.set.csv.file.path=
product.model.directory.path=models/product

lyrics.training.set.directory.path=training-set
lyrics.model.directory.path=models/lyrics

mendeley.csv.file.path=d:/projects/spark-ml-samples/merged_dataset.csv

# Selection from 7 possible pipelines: LogisticRegressionPipeline, NaiveBayesBagOfWordsPipeline, NaiveBayesTFIDFPipeline, RandomForestPipeline, FeedForwardNeuralNetworkPipeline, MendeleyNaiveBayesPipeline and MendeleyLogisticRegressionPipeline
lyrics.pipeline=MendeleyLogisticRegressionPipeline

mnist.training.set.image.file.path=
mnist.training.set.label.file.path=
mnist.test.set.image.file.path=
mnist.test.set.label.file.path=

mnist.training.set.parquet.file.path=
mnist.test.set.parquet.file.path=
mnist.model.directory.path=models/mnist
mnist.validation.set.directory.path=